namespace VavilichevGD.Tools {
    public enum BigNumberOrder {
        Singles = 0,
        Thousands = 1,
        Millions = 2,
        Billions = 3,
        Trillions = 4,
        AA = 5,
        BB = 6,
        CC = 7,
        DD = 8,
        EE = 9,
        FF = 10,
        GG = 11,
        HH = 12,
        II = 13,
        JJ = 14,
        KK = 15,
        LL = 16,
        MM = 17,
        NN = 18,
        OO = 19,
        PP = 20,
        QQ = 21,
        RR = 22,
        SS = 23,
        TT = 24,
        UU = 25,
        VV = 26,
        WW = 27,
        XX = 28,
        YY = 29,
        ZZ = 30
    }
}