// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_15 = "CgkIkfWUrucQEAIQDw"; // <GPGSID>
        public const string achievement_11 = "CgkIkfWUrucQEAIQCw"; // <GPGSID>
        public const string achievement__80 = "CgkIkfWUrucQEAIQEQ"; // <GPGSID>
        public const string achievement_13 = "CgkIkfWUrucQEAIQDQ"; // <GPGSID>
        public const string achievement_17 = "CgkIkfWUrucQEAIQEg"; // <GPGSID>
        public const string achievement_18 = "CgkIkfWUrucQEAIQFA"; // <GPGSID>
        public const string achievement_12 = "CgkIkfWUrucQEAIQDA"; // <GPGSID>
        public const string achievement_9 = "CgkIkfWUrucQEAIQCQ"; // <GPGSID>
        public const string achievement_2 = "CgkIkfWUrucQEAIQAw"; // <GPGSID>
        public const string achievement_3 = "CgkIkfWUrucQEAIQBA"; // <GPGSID>
        public const string achievement = "CgkIkfWUrucQEAIQAg"; // <GPGSID>
        public const string achievement_6 = "CgkIkfWUrucQEAIQBw"; // <GPGSID>
        public const string achievement_7 = "CgkIkfWUrucQEAIQBg"; // <GPGSID>
        public const string achievement_4 = "CgkIkfWUrucQEAIQBQ"; // <GPGSID>
        public const string achievement_5 = "CgkIkfWUrucQEAIQEw"; // <GPGSID>
        public const string achievement_8 = "CgkIkfWUrucQEAIQCA"; // <GPGSID>
        public const string achievement_10 = "CgkIkfWUrucQEAIQCg"; // <GPGSID>
        public const string achievement_16 = "CgkIkfWUrucQEAIQEA"; // <GPGSID>
        public const string achievement_14 = "CgkIkfWUrucQEAIQDg"; // <GPGSID>
        public const string achievement_19 = "CgkIkfWUrucQEAIQAA"; // <GPGSID>

}

